server:
  servlet:
    context-path: /marks-api
  port: 8082
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentsdata
    username: root
    password: popo1990
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true